### ISSUE TITLE
RegexWithGroup only works if every char in the string is inside a group.

### ISSUE THREAD

**Issue by jonaswre** [hediet/typed-lexer#2]
First of all let me say this project is great.

Im having trubble with the selection of regex groups. It seems like you are selecting the content of groups by yourself. 
`
        const t2 = tokens as TokenWithPosAndLen<TToken>[];
        
        let pos = 0;
        for (const t of t2) {
            t.startPos = pos;
            pos += t.length;
        }
        
        return this.tokensWithPos(t2, nextState);
` 

You start always start selecting on the first char. even if the groups starts on the second char.

If thinks it might be best to let regex handel the selection. So just use the match for the content.

Current workround is to make every char contained in a group then set unwanted groups to null and filter for null tokens afterwords. Thats seems a bit exessive.

**Comment by hediet** [comment]
Thanks for you input! I think my original idea was that every character is contained in a token, i.e. joining all token contents would give back the original string.

I have to revisit this project to think about it.
Also, I planned to rewrite this lib soon anyways. The use of classes here is questionable ;)
